### ISSUE TITLE
A tour interpreting the anonymized data

### ISSUE THREAD

**Issue by andyweizhao** [MicrosoftTranslator/ToShipOrNotToShip#1]
Hi, 

thanks very much for sharing the code!

We want to use the data in another scenario. Sadly, this seems a bit difficult task, as many details in data are anonymized, e.g., what do the anonymized directory and file names stand for?

Would you like to provide us a tour interpreting the anonymized data (maybe the data format, too)?

A side question: I found, in a .xlsx file, a segment_id is associated with up to 5 human scores; so, I guess different system translations are rated by different numbers of annotators, right? 

Best,
Wei

**Comment by ahoho** [comment]
Having poked around a bit, the folders appear to correspond to "campaigns" (see the paper for an explanation) and each Excel file within that folder contains system annotations. [`load_data()`](https://github.com/MicrosoftTranslator/ToShipOrNotToShip/blob/main/evaluation/tools.py) in `evaluation/tools.py` was helpful for understanding the structure.

**Comment by kocmitom** [comment]
Hi Wei and Alexander,

thank you for the issues, please add any that you'd come to. After I will return from vacation, I would look into them. I apologize for not having a proper description of the data before release (a lot of context is hidden due anonymization).

In short: each folder in public_release contains individual campaign folder. Each of these folders then contain individual xlsx files each representing a single system. 
Within the xlsx files, you always have "hum_annotations" where each line is single sentence (you can use SegmentID to map sentences between systems within single campaign), and then "automatic_metrics" that contains all system-level metrics and other metadata. 
There can be two more sheets: "hum_only_automatic_metrics" and "full_testset" - they contain larger testsets evaluated by automatic metrics only in case we subsampled from it for human evaluation.

Have a lovely day,
Tom

**Comment by PierreColombo** [comment]
Hi !
Thanks for your amazing work !
Any new on the quick tutorial ?
Thanks again for your work!

**Comment by kocmitom** [comment]
Hi All,

two days ago I returned from vacation and now I am going through the issues. I have extended the description in the README.md, let me know if there is still something that is confusing or should be better explained.

Have a lovely day,
Tom
