### ISSUE TITLE
Fewer examples provided than listed in publication

### ISSUE THREAD

**Issue by ahoho** [MicrosoftTranslator/ToShipOrNotToShip#2]
Thanks so much for putting up this data! I think it's really valuable for the field.

I'm finding that the number of annotated examples in the repo is 259 284, about an order of magnitude less than what's listed in the original paper (2.3M). Will the full data be made available, or am I getting something wrong?

On a related note, it appears the bootstrap data (`final_boostrap.pickle`), and/or the means of reproducing it, is unavailable.

(Edit: Noting the readme suggests I contact @kocmitom, so I am doing so)

**Comment by kocmitom** [comment]
Hi Alexander,

it was a bit hectic to get approval for the release. After I get back from vacation, I will write a proper description and check the errors.

As for the total number of annotations: if you run the script, it should generate a macros file that is sourced from the paper and in it, there should be the following two lines:
\def\totalannotations{2323625}
\def\totalannotationsMillions{2.3 M}

If they are different, that means we didn't release all data and I will find out where was the problem and do release them. Same for the bootstrap results (this file only contains data to replicate our results with statistical significance testing of metrics).

**Comment by ahoho** [comment]
Thanks for the response! I seem to get

```
\def\totalannotations{259284}
\def\totalannotationsMillions{0.3 M}
```

so the majority does appear to be missing (by the way, I really appreciate the replicability of using latex macros; I will have to adopt this as well).

In order to run without errors, I have to delete the `"bootstrap"` scenario in settings, so I assume that something is missing there (although, yeah, I think this is less critical).

Enjoy your vacation!

**Comment by ahoho** [comment]
Hi, wondering if there's an update on this? (Apologies if you are still on vacation!)

**Comment by cfedermann** [comment]
Tom is traveling and will only be able to get back to this thread starting
next week, sorry.

**Comment by kocmitom** [comment]
Hi Alexander, I returned from vacation on Saturday and now I am going through the issues. I just uploaded all missing files and it should give you identical results as in the paper. There is potentially one campaign out of 1728 missing which I am just investigating.

**Comment by ahoho** [comment]
Amazing! Thank you so much, hope your vacation was restful 🙂

**Comment by kocmitom** [comment]
It was awesome and really needed after this year :). Btw. there was a single campaign missing and also a bootstrap resampling pickle was missing.
